### ISSUE TITLE
solr proximity / phrase searching

### ISSUE THREAD

**Issue by jduss4** [CDRH/data#46]
The cody archive api schema behaves differently than the original.  If you search "pine ridge" the old site will do highlighting (and relevance) for both words whereas the new core will emphasize the first word only.  On the api site you can put the search in quotation marks to zero in, but the phrase searching should be behaving differently than this.

This may be a problem for other api sites, also.  Austen was not stemming "pie" a few weeks ago, as Andy was good enough to point out to us.

@karindalziel

**Comment by karindalziel** [comment]
The pie stemming was due to the stemming factory. I'm going to close this since we'll be putting cather in the api anyway.
