### ISSUE TITLE
es branch: clear solr seems not to work

### ISSUE THREAD

**Issue by karindalziel** [CDRH/data#70]
When I tried to clear a solr index on the _es branch I got an error: 

![screen shot 2017-07-10 at 2 23 35 pm](https://user-images.githubusercontent.com/284315/28035828-a71a970a-657b-11e7-8f90-dbe0de27ea5b.png)

No hurry to fix, I can still clear using the old data repo

**Comment by jduss4** [comment]
This has been fixed!
