### ISSUE TITLE
Check existing schema before posting to ES

### ISSUE THREAD

**Issue by jduss4** [CDRH/data#78]
Probably in datamanager, before pushing to index check if there is a schema for given _type and shut everything down if there's not.

Then, slightly weirder because it will happen every time (?), check the fields about to be sent to ES for any fields with no type and no _t setting and end the script, then tell the user that they either need to add that field to the schema, or they need to append a type to the field.

Think about how that last one will be implemented that won't require lots of calls or json checks, etc.

**Comment by techgique** [comment]
Added in #82
